export const SOURCE_DEFINITIONS = [
  {
    id: "openai-news",
    name: "开放人工智能公司",
    url: "https://openai.com/news/rss.xml",
    type: "official",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.42,
    maxItems: 12
  },
  {
    id: "google-ai-blog",
    name: "谷歌人工智能博客",
    url: "https://blog.google/technology/ai/rss/",
    type: "official",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.36,
    maxItems: 10
  },
  {
    id: "google-research",
    name: "谷歌研究院",
    url: "https://research.google/blog/rss/",
    type: "research",
    language: "zh",
    originLanguage: "en",
    aiFocused: false,
    allowExternal: true,
    weight: 1.3,
    maxItems: 8
  },
  {
    id: "github-blog",
    name: "代码托管平台官方博客",
    url: "https://github.blog/feed/",
    type: "official",
    language: "zh",
    originLanguage: "en",
    aiFocused: false,
    allowExternal: true,
    weight: 1.24,
    maxItems: 8
  },
  {
    id: "github-changelog",
    name: "代码托管平台更新日志",
    url: "https://github.blog/changelog/feed/",
    type: "official",
    language: "zh",
    originLanguage: "en",
    aiFocused: false,
    allowExternal: true,
    weight: 1.2,
    maxItems: 8
  },
  {
    id: "nvidia-blog",
    name: "英伟达官方博客",
    url: "https://blogs.nvidia.com/feed/",
    type: "official",
    language: "zh",
    originLanguage: "en",
    aiFocused: false,
    allowExternal: true,
    weight: 1.28,
    maxItems: 8
  },
  {
    id: "microsoft-ai-blog",
    name: "微软云与人工智能博客",
    url: "https://azure.microsoft.com/en-us/blog/feed/",
    type: "official",
    language: "zh",
    originLanguage: "en",
    aiFocused: false,
    allowExternal: true,
    weight: 1.26,
    maxItems: 8
  },
  {
    id: "huggingface-blog",
    name: "模型社区博客",
    url: "https://huggingface.co/blog/feed.xml",
    type: "official",
    language: "zh",
    originLanguage: "en",
    aiFocused: false,
    allowExternal: true,
    weight: 1.18,
    maxItems: 8
  },
  {
    id: "techcrunch-ai",
    name: "科技创投媒体人工智能",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    type: "media",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.18,
    maxItems: 10
  },
  {
    id: "ars-technica-ai",
    name: "技术深度媒体人工智能",
    url: "https://arstechnica.com/tag/ai/feed/",
    type: "media",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.16,
    maxItems: 10
  },
  {
    id: "the-verge-ai",
    name: "前沿科技媒体人工智能",
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    type: "media",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.14,
    maxItems: 10
  },
  {
    id: "mit-tech-review-ai",
    name: "麻省理工科技评论人工智能",
    url: "https://www.technologyreview.com/topic/artificial-intelligence/feed/",
    type: "media",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.12,
    maxItems: 10
  },
  {
    id: "the-decoder",
    name: "人工智能解码媒体",
    url: "https://the-decoder.com/feed/",
    type: "media",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.1,
    maxItems: 10
  },
  {
    id: "arxiv-cs-ai",
    name: "论文预印本：人工智能",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending&max_results=24",
    type: "research",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.16,
    maxItems: 8
  },
  {
    id: "arxiv-cs-lg",
    name: "论文预印本：机器学习",
    url: "https://export.arxiv.org/api/query?search_query=cat:cs.LG&sortBy=submittedDate&sortOrder=descending&max_results=24",
    type: "research",
    language: "zh",
    originLanguage: "en",
    aiFocused: true,
    allowExternal: true,
    weight: 1.14,
    maxItems: 8
  },
  {
    id: "qbitai",
    name: "量子位",
    url: "https://www.qbitai.com/feed",
    type: "media",
    language: "zh",
    aiFocused: false,
    weight: 1.15,
    maxItems: 24
  },
  {
    id: "leiphone",
    name: "雷峰网",
    url: "https://www.leiphone.com/feed",
    type: "media",
    language: "zh",
    aiFocused: false,
    weight: 1.08,
    maxItems: 24
  },
  {
    id: "thirty-six-kr",
    name: "三十六氪",
    url: "https://www.36kr.com/feed",
    type: "media",
    language: "zh",
    aiFocused: false,
    weight: 1.02,
    maxItems: 20
  },
  {
    id: "ithome",
    name: "科技之家",
    url: "https://www.ithome.com/rss/",
    type: "media",
    language: "zh",
    aiFocused: false,
    weight: 0.98,
    maxItems: 24
  },
  {
    id: "oschina",
    name: "开源中国",
    url: "https://www.oschina.net/news/rss",
    type: "media",
    language: "zh",
    aiFocused: false,
    weight: 0.94,
    maxItems: 20
  },
  {
    id: "cnblogs-news",
    name: "博客园新闻",
    url: "https://feed.cnblogs.com/news/rss",
    type: "media",
    language: "zh",
    aiFocused: false,
    weight: 0.9,
    maxItems: 16
  }
];
